sharding.jdbc:
    datasource:
      names: ds0,ds1
      ds0:
        type: org.apache.commons.dbcp.BasicDataSource
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://localhost:3306/ds_0
        username: root
        password: root
      ds1:
        type: org.apache.commons.dbcp.BasicDataSource
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://localhost:3306/ds_1
        username: root
        password: root

    config.sharding:
      default-database-strategy:
        inline:
          sharding-column: id
          algorithm-expression: ds$->{id % 2}
      tables.t_user:
        actual-data-nodes: ds$->{0..1}.t_user$->{0..1}
        table-strategy.inline:
          sharding-column: id
          algorithm-expression: t_user$->{id % 2}
        key-generator-column-name: id
